
-- Default administrator login
-- Username: bipe
-- Password: Bipe@4455
INSERT INTO academic_years (label, start_date, end_date, is_current) VALUES ('2025-2026', '2025-07-01', '2026-06-30', 1);

INSERT INTO admins (username, full_name, email, password_hash) VALUES ('bipe', 'BIPE Administrator', 'bipevns@gmail.com', '$2y$12$uFAWl6hGt9DHJFgTymxMTe3mbMIA1yUVApjlHMBUqCk8KBsJ6vaS6');

INSERT INTO departments (name, code, short_name, icon, theme_color) VALUES
  ('CS Engineering', 'CSE', 'CSE', '💻', '#f59e0b'),
  ('Civil Engineering', 'CE', 'CE', '🏗️', '#14b8a6'),
  ('Electrical Engineering', 'EE', 'EE', '⚡', '#60a5fa'),
  ('Production Engineering', 'PE', 'PE', '⚙️', '#a78bfa'),
  ('Automobile Engineering', 'AE', 'AE', '🚗', '#fb7185'),
  ('Dairy Engineering', 'DE', 'DE', '🥛', '#86efac');

INSERT INTO mark_types (label, max_marks, sort_order) VALUES
  ('Sessional Exam I', 50, 10),
  ('Sessional Exam II', 50, 20),
  ('Pre Board', 50, 30),
  ('Assignment', 10, 40),
  ('Attendance', 10, 50),
  ('Practical / Lab', 25, 60);

-- Default faculty password for seeded approved accounts: Teach@1234
INSERT INTO teachers (department_id, teacher_code, full_name, email, password_hash, status, registered_at, approved_at) VALUES
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 'rk.cse', 'Prof. R.K. Sharma', 'rk.cse@bipe.local', '$2y$12$fFa34.zodDkltp9TkcemLuWhlVn59V1FuuBa2UPLS87Bagp7aKr1W', 'approved', NOW(), NOW()),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 'ak.ce', 'Prof. A.K. Singh', 'ak.ce@bipe.local', '$2y$12$fFa34.zodDkltp9TkcemLuWhlVn59V1FuuBa2UPLS87Bagp7aKr1W', 'approved', NOW(), NOW()),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 'sn.ee', 'Prof. S.N. Mishra', 'sn.ee@bipe.local', '$2y$12$fFa34.zodDkltp9TkcemLuWhlVn59V1FuuBa2UPLS87Bagp7aKr1W', 'approved', NOW(), NOW()),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 'mk.pe', 'Prof. M.K. Yadav', 'mk.pe@bipe.local', '$2y$12$fFa34.zodDkltp9TkcemLuWhlVn59V1FuuBa2UPLS87Bagp7aKr1W', 'approved', NOW(), NOW()),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 'dk.ae', 'Prof. D.K. Gupta', 'dk.ae@bipe.local', '$2y$12$fFa34.zodDkltp9TkcemLuWhlVn59V1FuuBa2UPLS87Bagp7aKr1W', 'approved', NOW(), NOW()),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 'pc.de', 'Prof. P.C. Verma', 'pc.de@bipe.local', '$2y$12$fFa34.zodDkltp9TkcemLuWhlVn59V1FuuBa2UPLS87Bagp7aKr1W', 'approved', NOW(), NOW());

INSERT INTO subjects (department_id, semester_no, subject_code, subject_name) VALUES
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 2, 'CSE-S2-01', 'Mathematics-II'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 2, 'CSE-S2-02', 'Applied Physics-II'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 2, 'CSE-S2-03', 'Introduction to IT Systems'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 2, 'CSE-S2-04', 'Fundamentals of Electrical & Electronics Engineering'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 2, 'CSE-S2-05', 'Engineering Mechanics'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 2, 'CSE-S2-06', 'Engineering Workshop Practice'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 2, 'CSE-S2-07', 'Environmental Sciences'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 4, 'CSE-S4-01', 'Data Structures using C'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 4, 'CSE-S4-02', 'Software Engineering'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 4, 'CSE-S4-03', 'Introduction to E-Governance'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 4, 'CSE-S4-04', 'Computer System Organization'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 4, 'CSE-S4-05', 'Project Management'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 4, 'CSE-S4-06', 'Scripting Languages (Python)'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 4, 'CSE-S4-07', 'Essence of Indian Knowledge and Tradition'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 6, 'CSE-S6-01', 'Development of Android Applications'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 6, 'CSE-S6-02', 'Cloud Computing'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 6, 'CSE-S6-03', 'Industrial Management and Entrepreneurship Development'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 6, 'CSE-S6-04', 'Data Science and Machine Learning'),
  ((SELECT id FROM departments WHERE name = 'CS Engineering'), 6, 'CSE-S6-05', 'Project'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 2, 'CE-S2-01', 'Mathematics-II'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 2, 'CE-S2-02', 'Applied Physics-II'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 2, 'CE-S2-03', 'Introduction to IT Systems'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 2, 'CE-S2-04', 'Fundamentals of Electrical & Electronics Engineering'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 2, 'CE-S2-05', 'Engineering Mechanics'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 2, 'CE-S2-06', 'Engineering Workshop Practice'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 2, 'CE-S2-07', 'Environmental Sciences'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-01', 'Hydraulics'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-02', 'Hydraulics Lab'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-03', 'Advance Surveying'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-04', 'Advance Surveying Lab'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-05', 'Theory Of Structure'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-06', 'Design Of Reinforced Cement Concrete Structures'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-07', 'Reinforced Cement Concrete Structures Drawing'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-08', 'Water Resource Engineering'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-09', 'Public Health Engineering'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 4, 'CE-S4-10', 'Essence Of Indian Knowledge And Tradition'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 6, 'CE-S6-01', 'Quantity Surveying and Valuation'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 6, 'CE-S6-02', 'Construction Management, Accounts and Entrepreneurship Development'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 6, 'CE-S6-03', 'Design of Steel Structure'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 6, 'CE-S6-04', 'Steel Structure Drawing'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 6, 'CE-S6-05', 'Software Applications in Civil Engineering'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 6, 'CE-S6-06', 'Repair and Maintenance of Buildings'),
  ((SELECT id FROM departments WHERE name = 'Civil Engineering'), 6, 'CE-S6-07', 'Project Work'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 2, 'EE-S2-01', 'Mathematics-II'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 2, 'EE-S2-02', 'Applied Physics-II'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 2, 'EE-S2-03', 'Introduction to IT Systems'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 2, 'EE-S2-04', 'Fundamentals of Electrical & Electronics Engineering'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 2, 'EE-S2-05', 'Engineering Mechanics'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 2, 'EE-S2-06', 'Engineering Workshop Practice'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 2, 'EE-S2-07', 'Environmental Sciences'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-01', 'Electric Power Transmission And Distribution'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-02', 'Electric Machine-II'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-03', 'Fundamentals Of Power Electronics'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-04', 'Industrial Automation And Control'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-05', 'Renewable Energy Power Plants'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-06', 'Electric Machine-II (Lab)'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-07', 'Economic Policies In India'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 4, 'EE-S4-08', 'Essence Of Indian Knowledge And Tradition'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 6, 'EE-S6-01', 'Installation, Maintenance and Repair of Electrical Equipment'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 6, 'EE-S6-02', 'Electrical Design, Drawing and Estimating II'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 6, 'EE-S6-03', 'Utilization of Electrical Energy'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 6, 'EE-S6-04', 'Application of Computer Software in Electrical Engineering'),
  ((SELECT id FROM departments WHERE name = 'Electrical Engineering'), 6, 'EE-S6-05', 'Project Work'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 2, 'PE-S2-01', 'Mathematics-II'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 2, 'PE-S2-02', 'Applied Physics-II'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 2, 'PE-S2-03', 'Introduction to IT Systems'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 2, 'PE-S2-04', 'Fundamentals of Electrical & Electronics Engineering'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 2, 'PE-S2-05', 'Engineering Mechanics'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 2, 'PE-S2-06', 'Engineering Workshop Practice'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 2, 'PE-S2-07', 'Environmental Sciences'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-01', 'Strength of Materials'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-02', 'Industrial Engineering & Management'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-03', 'Strength of Materials Lab'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-04', 'Manufacturing Engineering'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-05', 'Material Science & Engineering'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-06', 'Thermal Engineering-II'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-07', 'Refrigeration & Air-conditioning'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 4, 'PE-S4-08', 'Essence of Indian Knowledge and Tradition'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 6, 'PE-S6-01', 'Industrial Engineering'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 6, 'PE-S6-02', 'Metrology and Measuring Instruments'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 6, 'PE-S6-03', 'CNC Machines and Automation'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 6, 'PE-S6-04', 'Tool Engineering'),
  ((SELECT id FROM departments WHERE name = 'Production Engineering'), 6, 'PE-S6-05', 'Project Work'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 2, 'AE-S2-01', 'Mathematics-II'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 2, 'AE-S2-02', 'Applied Physics-II'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 2, 'AE-S2-03', 'Introduction to IT Systems'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 2, 'AE-S2-04', 'Fundamentals of Electrical & Electronics Engineering'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 2, 'AE-S2-05', 'Engineering Mechanics'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 2, 'AE-S2-06', 'Engineering Workshop Practice'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 2, 'AE-S2-07', 'Environmental Sciences'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-01', 'Strength of Materials'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-02', 'Industrial Engineering & Management'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-03', 'Strength of Materials Lab'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-04', 'Manufacturing Engineering'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-05', 'Material Science & Engineering'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-06', 'Thermal Engineering-II'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-07', 'Refrigeration & Air-conditioning'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 4, 'AE-S4-08', 'Essence of Indian Knowledge and Tradition'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 6, 'AE-S6-01', 'Industrial Engineering'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 6, 'AE-S6-02', 'Metrology and Measuring Instruments'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 6, 'AE-S6-03', 'CNC Machines and Automation'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 6, 'AE-S6-04', 'Automobile Maintenance, Servicing & Repair'),
  ((SELECT id FROM departments WHERE name = 'Automobile Engineering'), 6, 'AE-S6-05', 'Project Work'),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 2, 'DE-S2-01', 'Mathematics-II'),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 2, 'DE-S2-02', 'Applied Physics-II'),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 2, 'DE-S2-03', 'Introduction to IT Systems'),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 2, 'DE-S2-04', 'Fundamentals of Electrical & Electronics Engineering'),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 2, 'DE-S2-05', 'Engineering Mechanics'),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 2, 'DE-S2-06', 'Engineering Workshop Practice'),
  ((SELECT id FROM departments WHERE name = 'Dairy Engineering'), 2, 'DE-S2-07', 'Environmental Sciences');

